travis:
  secure:
    BINSTAR_TOKEN: FgtyVvLmgSbe8MUWYHcMUn4Z//nURyg9GUp4QarBjzTPdZZjzrxrFPOPAbsv4BYRK2fJhzF5XL50UbaoqCYxvPk7JZSaQ34mWFD8M3MgYjP+8L5fVrvXhEmoipPq0/zANUcGlmS1bl520+cmDMAgPdGtxzbVWl/MbQFz7zZQ4cG0tdbr1xig8xr3xxpNYhUhjDPtqLUQucstwWntiexj1UPfzDVRewb0bQo9Zpc1HDGXJ4y8X/KXDfoy92VTEAfDPnD7Yta6Uj562h8sn5z5HVzl7zGL3bU8g90SyxN7VV4Upp/nNfR+xzZYmbNnFoHi8L3V8hzhG9tkhOMGtkVx5coPFqowL53uHwY3hRb1OMsWFITTD8wiR48wSkyij2QaIbu0LLPKZBeIj+U6943Ht2M85g3bbo7trLcAfgJTI4rJZbOknwxwjZIIM+GsNDnufcBy6wpvfSMA+qiKy5M0QCiWdhW7vq2d+nttF/u7ziu10Sjyx6iyT8jZP8IrAjB96ltXKNkHF+hgzxxZSidr7fh7PzyXhX2B1CU2ZNtiNc0PqQrF9rpt0iTjJdzYrtflQreIwMJJTjCJ+t0AA+C0mC9m+da6uYRC7TXhg5QjcA39nIaRt9n7jKSo/Qc3JXAOk+wxQwmxHbAY3uYyduC8YYN1Cl0HCgiayBg+I7WbZgE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
